import type { Item } from "./types";

export const ITEMS: Item[] = [
  { id: "w_rusty_sword", name: "Rusty Sword", emoji: "🗡️", slot: "weapon", rarity: "common", stats: { attack: 14 } },
  { id: "w_wooden_club", name: "Wooden Club", emoji: "🏏", slot: "weapon", rarity: "common", stats: { attack: 16, defense: 4 } },
  { id: "w_battle_axe", name: "Battle Axe", emoji: "🪓", slot: "weapon", rarity: "common", stats: { attack: 30, accuracy: -15 } },
  { id: "w_dagger", name: "Sly Dagger", emoji: "🔪", slot: "weapon", rarity: "common", stats: { attack: 10, speed: 14, critChance: 12 } },
  { id: "w_rapier", name: "Rapier", emoji: "🤺", slot: "weapon", rarity: "uncommon", stats: { attack: 18 }, passive: { type: "firstStrike", value: 1, label: "Always attacks first" } },
  { id: "w_bow", name: "Longbow", emoji: "🏹", slot: "weapon", rarity: "uncommon", stats: { attack: 20, critChance: 20 }, tags: ["ranged"] },
  { id: "w_war_hammer", name: "War Hammer", emoji: "🔨", slot: "weapon", rarity: "uncommon", stats: { attack: 42, accuracy: -35 } },
  { id: "w_spiked_flail", name: "Spiked Flail", emoji: "⛓️", slot: "weapon", rarity: "uncommon", stats: { attack: 24, accuracy: -10, critChance: 8 } },
  { id: "w_twin_blades", name: "Twin Blades", emoji: "⚔️", slot: "weapon", rarity: "rare", stats: { attack: 17 }, passive: { type: "extraAttack", value: 35, label: "35% chance to attack twice" } },
  { id: "w_poison_fang", name: "Poison Fang", emoji: "🐍", slot: "weapon", rarity: "rare", stats: { attack: 15 }, passive: { type: "poisonOnHit", value: 6, label: "Hits poison for 6 dmg per turn" } },
  { id: "w_crossbow", name: "Heavy Crossbow", emoji: "🎯", slot: "weapon", rarity: "rare", stats: { attack: 27, critChance: 12, speed: -8 }, tags: ["ranged"] },
  { id: "w_executioner", name: "Executioner Axe", emoji: "🪓", slot: "weapon", rarity: "epic", stats: { attack: 25 }, passive: { type: "executioner", value: 60, label: "+60% dmg vs targets below 35% HP" } },
  { id: "w_vampire_scythe", name: "Vampire Scythe", emoji: "🌙", slot: "weapon", rarity: "epic", stats: { attack: 23 }, passive: { type: "lifesteal", value: 25, label: "Heals 25% of damage dealt" } },
  { id: "w_storm_spear", name: "Storm Spear", emoji: "⚡", slot: "weapon", rarity: "epic", stats: { attack: 28, initiative: 12 }, passive: { type: "stunChance", value: 15, label: "15% chance to stun on hit" } },
  { id: "w_dragonfang", name: "Dragonfang Greatsword", emoji: "🐉", slot: "weapon", rarity: "legendary", stats: { attack: 36, critDamage: 40 }, passive: { type: "berserk", value: 50, label: "+50% attack below 40% HP" } },
  { id: "w_void_reaper", name: "Void Reaper", emoji: "💀", slot: "weapon", rarity: "legendary", stats: { attack: 32, accuracy: -10 }, passive: { type: "ignoreDefense", value: 60, label: "Ignores 60% of enemy defense" } },
  { id: "h_old_helmet", name: "Old Helmet", emoji: "🪖", slot: "helmet", rarity: "common", stats: { defense: 7 } },
  { id: "h_leather_cap", name: "Leather Cap", emoji: "🧢", slot: "helmet", rarity: "common", stats: { defense: 5, speed: 6 } },
  { id: "h_bucket", name: "Bucket Helm", emoji: "🪣", slot: "helmet", rarity: "common", stats: { defense: 13, accuracy: -12 } },
  { id: "h_iron_helm", name: "Iron Helm", emoji: "⛑️", slot: "helmet", rarity: "uncommon", stats: { defense: 11, speed: -4 }, tags: ["heavy"] },
  { id: "h_wizard_hat", name: "Wizard Hat", emoji: "🧙", slot: "helmet", rarity: "uncommon", stats: { defense: 5, critChance: 12 } },
  { id: "h_spiked_helm", name: "Spiked Helm", emoji: "📌", slot: "helmet", rarity: "uncommon", stats: { defense: 8 }, passive: { type: "reflect", value: 12, label: "Reflects 12% of damage taken" } },
  { id: "h_bascinet", name: "Visored Bascinet", emoji: "🛡️", slot: "helmet", rarity: "rare", stats: { defense: 10 }, passive: { type: "critResist", value: 40, label: "Takes 40% less critical damage" } },
  { id: "h_crown_vitality", name: "Crown of Vitality", emoji: "👑", slot: "helmet", rarity: "rare", stats: { defense: 4, hp: 35 } },
  { id: "h_bone_helm", name: "Bone Helm", emoji: "🦴", slot: "helmet", rarity: "rare", stats: { defense: 9, attack: 7 } },
  { id: "h_owl_helm", name: "Owl Helm", emoji: "🦉", slot: "helmet", rarity: "epic", stats: { defense: 8, dodge: 14, accuracy: 8 } },
  { id: "h_golden_crown", name: "Golden Crown", emoji: "👑", slot: "helmet", rarity: "epic", stats: { defense: 7, critChance: 10, dodge: 10 } },
  { id: "h_dragon_king", name: "Dragon King's Helmet", emoji: "🐲", slot: "helmet", rarity: "legendary", stats: { defense: 15, hp: 30 }, passive: { type: "critResist", value: 50, label: "Takes 50% less critical damage" } },
  { id: "h_phoenix_crest", name: "Phoenix Crest", emoji: "🔥", slot: "helmet", rarity: "legendary", stats: { defense: 9 }, passive: { type: "lastStand", value: 30, label: "Revives once at 30% HP" } },
  { id: "a_cloth_tunic", name: "Cloth Tunic", emoji: "👕", slot: "armor", rarity: "common", stats: { defense: 6, speed: 6 } },
  { id: "a_leather", name: "Leather Armor", emoji: "🧥", slot: "armor", rarity: "common", stats: { defense: 10 } },
  { id: "a_rusty_plate", name: "Rusty Chestplate", emoji: "🍂", slot: "armor", rarity: "common", stats: { defense: 13, dodge: -6 }, tags: ["heavy"] },
  { id: "a_chainmail", name: "Chainmail", emoji: "⛓️", slot: "armor", rarity: "uncommon", stats: { defense: 14, speed: -5 }, tags: ["heavy"] },
  { id: "a_mage_robe", name: "Mage Robe", emoji: "🥋", slot: "armor", rarity: "uncommon", stats: { defense: 7 }, passive: { type: "healPerTurn", value: 4, label: "Regenerates 4 HP per turn" } },
  { id: "a_gamblers_vest", name: "Gambler's Vest", emoji: "🎰", slot: "armor", rarity: "uncommon", stats: { defense: 8, critChance: 8 } },
  { id: "a_plate", name: "Plate Armor", emoji: "🛡️", slot: "armor", rarity: "rare", stats: { defense: 21, speed: -12 }, tags: ["heavy"] },
  { id: "a_shadow_cloak", name: "Shadow Cloak", emoji: "🌫️", slot: "armor", rarity: "rare", stats: { defense: 8, dodge: 16 } },
  { id: "a_thorned_mail", name: "Thorned Mail", emoji: "🌵", slot: "armor", rarity: "rare", stats: { defense: 12 }, passive: { type: "reflect", value: 20, label: "Reflects 20% of damage taken" } },
  { id: "a_berserker_harness", name: "Berserker Harness", emoji: "😤", slot: "armor", rarity: "epic", stats: { defense: 6, attack: 16 } },
  { id: "a_guardian_plate", name: "Guardian Plate", emoji: "🏰", slot: "armor", rarity: "epic", stats: { defense: 19, hp: 25 }, tags: ["heavy"] },
  { id: "a_titan", name: "Titan Armor", emoji: "🗿", slot: "armor", rarity: "legendary", stats: { defense: 30, speed: -18 }, passive: { type: "block", value: 25, label: "25% chance to block half damage" }, tags: ["heavy"] },
  { id: "a_dragonscale", name: "Dragonscale Armor", emoji: "🐊", slot: "armor", rarity: "legendary", stats: { defense: 22 }, passive: { type: "reflect", value: 15, label: "Reflects 15% of damage taken" } },
  { id: "b_worn", name: "Worn Boots", emoji: "🥾", slot: "boots", rarity: "common", stats: { speed: 7 } },
  { id: "b_sandals", name: "Sandals", emoji: "🩴", slot: "boots", rarity: "common", stats: { speed: 10, defense: -2 } },
  { id: "b_sturdy", name: "Sturdy Boots", emoji: "👢", slot: "boots", rarity: "common", stats: { speed: 5, defense: 5 } },
  { id: "b_iron_greaves", name: "Iron Greaves", emoji: "🦿", slot: "boots", rarity: "uncommon", stats: { defense: 8, speed: -4 }, tags: ["heavy"] },
  { id: "b_swift", name: "Swift Boots", emoji: "💨", slot: "boots", rarity: "uncommon", stats: { speed: 14, dodge: 6 } },
  { id: "b_spiked_cleats", name: "Spiked Cleats", emoji: "⚽", slot: "boots", rarity: "uncommon", stats: { speed: 7, attack: 6 } },
  { id: "b_winged", name: "Winged Boots", emoji: "🕊️", slot: "boots", rarity: "rare", stats: { speed: 16, initiative: 12 } },
  { id: "b_shadow_steps", name: "Shadow Steps", emoji: "👣", slot: "boots", rarity: "rare", stats: { speed: 9, dodge: 14 } },
  { id: "b_lucky_slippers", name: "Lucky Slippers", emoji: "🍀", slot: "boots", rarity: "rare", stats: { speed: 8, critChance: 8, dodge: 8 } },
  { id: "b_warlord", name: "Warlord Greaves", emoji: "⚙️", slot: "boots", rarity: "epic", stats: { speed: 9, defense: 9, attack: 6 } },
  { id: "b_earthshaker", name: "Earthshaker Boots", emoji: "🌋", slot: "boots", rarity: "epic", stats: { speed: 6, attack: 8 }, passive: { type: "stunChance", value: 12, label: "12% chance to stun on hit" } },
  { id: "b_hermes", name: "Hermes Treads", emoji: "🌪️", slot: "boots", rarity: "legendary", stats: { speed: 22 }, passive: { type: "firstStrike", value: 1, label: "Always attacks first" } },
  { id: "b_phantom", name: "Phantom Striders", emoji: "👻", slot: "boots", rarity: "legendary", stats: { speed: 13, dodge: 22, defense: -5 } },
  { id: "c_copper_ring", name: "Copper Ring", emoji: "💍", slot: "accessory", rarity: "common", stats: { hp: 12, attack: 4 } },
  { id: "c_iron_band", name: "Iron Band", emoji: "⭕", slot: "accessory", rarity: "common", stats: { defense: 6 } },
  { id: "c_lucky_coin", name: "Lucky Coin", emoji: "🪙", slot: "accessory", rarity: "uncommon", stats: { critChance: 14 } },
  { id: "c_healing_pendant", name: "Healing Pendant", emoji: "💚", slot: "accessory", rarity: "uncommon", stats: {}, passive: { type: "healPerTurn", value: 6, label: "Regenerates 6 HP per turn" } },
  { id: "c_snake_ring", name: "Snake Ring", emoji: "🐍", slot: "accessory", rarity: "uncommon", stats: { attack: 5 }, passive: { type: "poisonOnHit", value: 4, label: "Hits poison for 4 dmg per turn" } },
  { id: "c_vampire_necklace", name: "Vampire Necklace", emoji: "🧛", slot: "accessory", rarity: "rare", stats: {}, passive: { type: "lifesteal", value: 22, label: "Heals 22% of damage dealt" } },
  { id: "c_mirror_amulet", name: "Mirror Amulet", emoji: "🪞", slot: "accessory", rarity: "rare", stats: {}, passive: { type: "reflect", value: 25, label: "Reflects 25% of damage taken" } },
  { id: "c_clover", name: "Four-Leaf Clover", emoji: "🍀", slot: "accessory", rarity: "rare", stats: { dodge: 10, critChance: 10, accuracy: 6 } },
  { id: "c_poison_vial", name: "Poison Vial", emoji: "🧪", slot: "accessory", rarity: "rare", stats: {}, passive: { type: "poisonOnHit", value: 8, label: "Hits poison for 8 dmg per turn" } },
  { id: "c_berserker_totem", name: "Berserker Totem", emoji: "🗿", slot: "accessory", rarity: "epic", stats: { attack: 14, defense: -8 } },
  { id: "c_guardian_charm", name: "Guardian Charm", emoji: "🔮", slot: "accessory", rarity: "epic", stats: {}, passive: { type: "shield", value: 30, label: "Starts battle with a 30 HP shield" } },
  { id: "c_assassins_mark", name: "Assassin's Mark", emoji: "🎭", slot: "accessory", rarity: "epic", stats: { critChance: 20, critDamage: 30 } },
  { id: "c_cursed_skull", name: "Cursed Skull", emoji: "💀", slot: "accessory", rarity: "epic", stats: { attack: 24, hp: -25 } },
  { id: "c_phoenix_feather", name: "Phoenix Feather", emoji: "🪶", slot: "accessory", rarity: "legendary", stats: {}, passive: { type: "lastStand", value: 40, label: "Revives once at 40% HP" } },
  { id: "c_chaos_orb", name: "Chaos Orb", emoji: "🌀", slot: "accessory", rarity: "legendary", stats: {}, passive: { type: "chaos", value: 35, label: "All your stats shift ±35% each battle" } }
];

export function itemById(id: string): Item | undefined {
  return ITEMS.find((i) => i.id === id);
}
