import Foundation

typealias LangPair = (en: String, tr: String)

enum ContentStrings {
    static let ui: [String: LangPair] = [
        "tagline": ("Draft chaotic gear. Gamble on luck. Watch your friends fall.", "Çılgın eşyalar seç. Şansa oyna. Arkadaşlarının düşüşünü izle."),
        "yourNickname": ("Your nickname", "Takma adın"),
        "nickPlaceholder": ("e.g. AxeLord", "örn. BaltaBey"),
        "createRoom": ("🎮 Create Room", "🎮 Oda Kur"),
        "creating": ("Creating...", "Oda kuruluyor..."),
        "orJoin": ("or join a friend", "veya bir arkadaşına katıl"),
        "roomCodePlaceholder": ("ROOM CODE", "ODA KODU"),
        "join": ("Join", "Katıl"),
        "footer": ("2–8 players · everyone on their own phone · loudest room wins", "2–8 oyuncu · herkes kendi telefonundan · en gürültülü oda kazanır"),
        "nickTooShort": ("Nickname must be at least 2 characters.", "Takma ad en az 2 karakter olmalı."),
        "codeLength": ("Room codes are 6 characters.", "Oda kodları 6 karakterdir."),
        "serverUnreachable": ("Could not reach the server. Check your connection and try again.", "Sunucuya ulaşılamadı. Bağlantını kontrol edip tekrar dene."),
        "serverAddress": ("Server address", "Sunucu adresi"),
        "roomCode": ("Room code", "Oda kodu"),
        "joinHint": ("Friends join at this address with the code above", "Arkadaşların bu adrese girip yukarıdaki kodla katılır"),
        "warriors": ("Warriors", "Savaşçılar"),
        "you": ("YOU", "SEN"),
        "offline": ("offline", "çevrimdışı"),
        "startDraft": ("⚔️ Start the Draft", "⚔️ Seçimi Başlat"),
        "startWithBots": ("🤖 Play Solo vs 3 Bots", "🤖 Tek Başına 3 Bota Karşı Oyna"),
        "waitingHost": ("Waiting for the host to start...", "Kurucunun başlatması bekleniyor..."),
        "draft": ("Draft", "Seçim"),
        "pickOne": ("Pick ONE item. The slot locks forever.", "SADECE BİR eşya seç. O yuva sonsuza dek kilitlenir."),
        "slotOccupied": ("🔒 Slot already occupied", "🔒 Bu yuva zaten dolu"),
        "lockedIn": ("Locked in!", "Seçim yapıldı!"),
        "waitingSlow": ("Waiting for the slowpokes...", "Yavaş kalanlar bekleniyor..."),
        "skipRound": ("😱 Every slot is taken — skip this round", "😱 Tüm yuvalar dolu — bu turu pas geç"),
        "luckTitle": ("🍀 Luck Cards", "🍀 Şans Kartları"),
        "luckSub": ("One card. It might save you. It might not.", "Tek kart. Seni kurtarabilir. Ya da kurtarmayabilir."),
        "fateSealed": ("Your fate is sealed.", "Kaderin mühürlendi."),
        "waitingGamble": ("Waiting for the others to gamble...", "Diğerlerinin kumarı bekleniyor..."),
        "globalEvent": ("Global Event", "Küresel Olay"),
        "tournamentBegins": ("⚔️ The tournament begins...", "⚔️ Turnuva başlıyor..."),
        "tournament": ("🏆 Tournament", "🏆 Turnuva"),
        "grandFinal": ("GRAND FINAL", "BÜYÜK FİNAL"),
        "semifinal": ("Semifinal", "Yarı Final"),
        "round": ("Round {n}", "{n}. Tur"),
        "bye": ("(bye)", "(bay geçti)"),
        "champion": ("Champion", "Şampiyon"),
        "thatsYou": ("THAT'S YOU! Rub it in. 😎", "BU SENSİN! Bol bol caka sat. 😎"),
        "finalStandings": ("Final standings", "Nihai sıralama"),
        "wins": ("wins", "galibiyet"),
        "oneMoreGame": ("🔄 ONE MORE GAME!", "🔄 BİR EL DAHA!"),
        "shoutHost": ("Shout at the host to run it back.", "Tekrar oynamak için kurucuya bağır."),
        "leave": ("← Leave", "← Ayrıl"),
        "room": ("Room", "Oda"),
        "loading": ("Loading...", "Yükleniyor..."),
        "joining": ("Joining", "Katılınıyor"),
        "enterArena": ("Enter the Arena", "Arenaya Gir"),
        "headingHome": ("Heading back home...", "Ana sayfaya dönülüyor..."),
        "extraAttackPrefix": ("⚡ Extra attack! ", "⚡ Ekstra saldırı! "),
        "bigMiss": ("MISS!", "ISKA!"),
        "bigDodge": ("DODGED!", "KAÇINDI!"),
        "bigCrit": ("CRITICAL!", "KRİTİK!"),
        "bigDamage": ("DAMAGE", "HASAR"),
        "critBit": ("💥 CRITICAL HIT!", "💥 KRİTİK VURUŞ!"),
        "blockBit": ("🛡️ Partially blocked!", "🛡️ Kısmen engellendi!"),
        "shieldBit": ("✨ Shield absorbs {n}!", "✨ Kalkan {n} hasar emdi!"),
        "fists": ("fists", "yumruklar"),
        "chooseFighter": ("Choose your fighter", "Savaşçını seç"),
        "bareHands": ("Bare fists", "Çıplak yumruklar"),
        "battleGear": ("Battle gear", "Savaş teçhizatı"),
        "err_nickname": ("Enter a nickname (2-16 characters).", "Bir takma ad gir (2-16 karakter)."),
        "err_not_found": ("Room not found. Check the code.", "Oda bulunamadı. Kodu kontrol et."),
        "err_started": ("This match already started. Wait for the next one!", "Bu maç çoktan başladı. Bir sonrakini bekle!"),
        "err_full": ("Room is full (8 players max).", "Oda dolu (en fazla 8 oyuncu)."),
        "err_taken": ("That nickname is taken in this room.", "Bu takma ad bu odada zaten alınmış."),
        "err_host_start": ("Only the host can start the game.", "Oyunu yalnızca kurucu başlatabilir."),
        "err_host_restart": ("Only the host can restart.", "Yalnızca kurucu yeniden başlatabilir."),
        "err_busy": ("The server is busy, try again in a moment.", "Sunucu meşgul, birazdan tekrar dene."),
        "err_unknown": ("Something went wrong. Try again.", "Bir şeyler ters gitti. Tekrar dene."),
        "common": ("Common", "Sıradan"),
        "uncommon": ("Uncommon", "Alışılmadık"),
        "rare": ("Rare", "Nadir"),
        "epic": ("Epic", "Destansı"),
        "legendary": ("Legendary", "Efsanevi"),
        "slot_weapon": ("Weapon", "Silah"),
        "slot_helmet": ("Helmet", "Miğfer"),
        "slot_armor": ("Armor", "Zırh"),
        "slot_boots": ("Boots", "Botlar"),
        "slot_accessory": ("Accessory", "Aksesuar"),
        "stat_attack": ("ATK", "SAL"),
        "stat_defense": ("DEF", "SAV"),
        "stat_hp": ("HP", "CAN"),
        "stat_speed": ("SPD", "HIZ"),
        "stat_critChance": ("CRIT%", "KRİT%"),
        "stat_critDamage": ("CRIT DMG", "KRİT HSR"),
        "stat_accuracy": ("ACC", "İSAB"),
        "stat_dodge": ("DODGE", "KAÇIN"),
        "stat_initiative": ("INIT", "İNİS"),
        "avatar_blaze": ("Blaze", "Alaz"),
        "avatar_shadow": ("Shadow", "Gölge"),
        "avatar_viking": ("Viking", "Viking"),
        "avatar_ronin": ("Ronin", "Ronin"),
        "avatar_corsair": ("Corsair", "Korsan"),
        "avatar_mystic": ("Mystic", "Mistik"),
        "avatar_golem": ("Golem", "Golem"),
        "avatar_punk": ("Punk", "Punk"),
        "avatar_valkyrie": ("Valkyrie", "Valkür"),
        "avatar_monk": ("Monk", "Keşiş"),
        "avatar_frost": ("Frost", "Ayaz"),
        "avatar_minotaur": ("Minotaur", "Boğa")
    ]

    static let itemNamesEN: [String: String] = [
        "w_rusty_sword": "Rusty Sword", "w_wooden_club": "Wooden Club", "w_battle_axe": "Battle Axe",
        "w_dagger": "Sly Dagger", "w_rapier": "Rapier", "w_bow": "Longbow", "w_war_hammer": "War Hammer",
        "w_spiked_flail": "Spiked Flail", "w_twin_blades": "Twin Blades", "w_poison_fang": "Poison Fang",
        "w_crossbow": "Heavy Crossbow", "w_executioner": "Executioner Axe", "w_vampire_scythe": "Vampire Scythe",
        "w_storm_spear": "Storm Spear", "w_dragonfang": "Dragonfang Greatsword", "w_void_reaper": "Void Reaper",
        "h_old_helmet": "Old Helmet", "h_leather_cap": "Leather Cap", "h_bucket": "Bucket Helm",
        "h_iron_helm": "Iron Helm", "h_wizard_hat": "Wizard Hat", "h_spiked_helm": "Spiked Helm",
        "h_bascinet": "Visored Bascinet", "h_crown_vitality": "Crown of Vitality", "h_bone_helm": "Bone Helm",
        "h_owl_helm": "Owl Helm", "h_golden_crown": "Golden Crown", "h_dragon_king": "Dragon King's Helmet",
        "h_phoenix_crest": "Phoenix Crest",
        "a_cloth_tunic": "Cloth Tunic", "a_leather": "Leather Armor", "a_rusty_plate": "Rusty Chestplate",
        "a_chainmail": "Chainmail", "a_mage_robe": "Mage Robe", "a_gamblers_vest": "Gambler's Vest",
        "a_plate": "Plate Armor", "a_shadow_cloak": "Shadow Cloak", "a_thorned_mail": "Thorned Mail",
        "a_berserker_harness": "Berserker Harness", "a_guardian_plate": "Guardian Plate", "a_titan": "Titan Armor",
        "a_dragonscale": "Dragonscale Armor",
        "b_worn": "Worn Boots", "b_sandals": "Sandals", "b_sturdy": "Sturdy Boots",
        "b_iron_greaves": "Iron Greaves", "b_swift": "Swift Boots", "b_spiked_cleats": "Spiked Cleats",
        "b_winged": "Winged Boots", "b_shadow_steps": "Shadow Steps", "b_lucky_slippers": "Lucky Slippers",
        "b_warlord": "Warlord Greaves", "b_earthshaker": "Earthshaker Boots", "b_hermes": "Hermes Treads",
        "b_phantom": "Phantom Striders",
        "c_copper_ring": "Copper Ring", "c_iron_band": "Iron Band", "c_lucky_coin": "Lucky Coin",
        "c_healing_pendant": "Healing Pendant", "c_snake_ring": "Snake Ring", "c_vampire_necklace": "Vampire Necklace",
        "c_mirror_amulet": "Mirror Amulet", "c_clover": "Four-Leaf Clover", "c_poison_vial": "Poison Vial",
        "c_berserker_totem": "Berserker Totem", "c_guardian_charm": "Guardian Charm", "c_assassins_mark": "Assassin's Mark",
        "c_cursed_skull": "Cursed Skull", "c_phoenix_feather": "Phoenix Feather", "c_chaos_orb": "Chaos Orb"
    ]

    static let itemNamesTR: [String: String] = [
        "w_rusty_sword": "Paslı Kılıç", "w_wooden_club": "Tahta Sopa", "w_battle_axe": "Savaş Baltası",
        "w_dagger": "Sinsi Hançer", "w_rapier": "İnce Kılıç", "w_bow": "Uzun Yay", "w_war_hammer": "Savaş Çekici",
        "w_spiked_flail": "Dikenli Topuz", "w_twin_blades": "İkiz Kılıçlar", "w_poison_fang": "Zehirli Diş",
        "w_crossbow": "Ağır Arbalet", "w_executioner": "Cellat Baltası", "w_vampire_scythe": "Vampir Tırpanı",
        "w_storm_spear": "Fırtına Mızrağı", "w_dragonfang": "Ejder Dişi Kılıcı", "w_void_reaper": "Hiçlik Orağı",
        "h_old_helmet": "Eski Miğfer", "h_leather_cap": "Deri Başlık", "h_bucket": "Kova Miğfer",
        "h_iron_helm": "Demir Miğfer", "h_wizard_hat": "Büyücü Şapkası", "h_spiked_helm": "Dikenli Miğfer",
        "h_bascinet": "Siperlikli Miğfer", "h_crown_vitality": "Yaşam Tacı", "h_bone_helm": "Kemik Miğfer",
        "h_owl_helm": "Baykuş Miğferi", "h_golden_crown": "Altın Taç", "h_dragon_king": "Ejderha Kralı Miğferi",
        "h_phoenix_crest": "Anka Sorgucu",
        "a_cloth_tunic": "Bez Tunik", "a_leather": "Deri Zırh", "a_rusty_plate": "Paslı Göğüslük",
        "a_chainmail": "Zincir Zırh", "a_mage_robe": "Büyücü Cübbesi", "a_gamblers_vest": "Kumarbaz Yeleği",
        "a_plate": "Plaka Zırh", "a_shadow_cloak": "Gölge Pelerini", "a_thorned_mail": "Dikenli Zırh",
        "a_berserker_harness": "Cinnet Zırhı", "a_guardian_plate": "Muhafız Zırhı", "a_titan": "Titan Zırhı",
        "a_dragonscale": "Ejder Pulu Zırhı",
        "b_worn": "Eskimiş Botlar", "b_sandals": "Sandaletler", "b_sturdy": "Sağlam Botlar",
        "b_iron_greaves": "Demir Dizlikler", "b_swift": "Çevik Botlar", "b_spiked_cleats": "Kramponlar",
        "b_winged": "Kanatlı Botlar", "b_shadow_steps": "Gölge Adımları", "b_lucky_slippers": "Şanslı Terlikler",
        "b_warlord": "Savaş Lordu Dizlikleri", "b_earthshaker": "Yer Sarsan Botlar", "b_hermes": "Hermes Sandaletleri",
        "b_phantom": "Hayalet Adımlıklar",
        "c_copper_ring": "Bakır Yüzük", "c_iron_band": "Demir Halka", "c_lucky_coin": "Şanslı Para",
        "c_healing_pendant": "Şifa Kolyesi", "c_snake_ring": "Yılan Yüzüğü", "c_vampire_necklace": "Vampir Kolyesi",
        "c_mirror_amulet": "Ayna Tılsımı", "c_clover": "Dört Yapraklı Yonca", "c_poison_vial": "Zehir Şişesi",
        "c_berserker_totem": "Cinnet Totemi", "c_guardian_charm": "Muhafız Tılsımı", "c_assassins_mark": "Suikastçı Nişanı",
        "c_cursed_skull": "Lanetli Kafatası", "c_phoenix_feather": "Anka Tüyü", "c_chaos_orb": "Kaos Küresi"
    ]

    static let eventsEN: [String: (name: String, description: String)] = [
        "rain": ("Rain", "A downpour soaks every bowstring. Ranged weapons deal 35% less damage."),
        "blood_moon": ("Blood Moon", "The moon turns red. Critical hits deal 50% more damage."),
        "blizzard": ("Blizzard", "Freezing winds slow everyone. Speed reduced by 35%."),
        "thunderstorm": ("Thunderstorm", "Legendary items crackle with power, granting +20% attack and defense to their owners."),
        "plague": ("Plague", "A sickness spreads. Everyone starts with 25% less HP."),
        "lucky_day": ("Lucky Day", "The humble shine today. Owners of Common items gain +15% attack and defense."),
        "tax_season": ("Tax Season", "The crown taxes the wealthy. Legendary owners lose 15% attack and defense."),
        "tornado": ("Tornado", "Chaotic winds decide who strikes first. Turn order is random every round."),
        "eclipse": ("Solar Eclipse", "Darkness covers the arena. Accuracy reduced by 20."),
        "full_moon": ("Full Moon", "Instincts sharpen under moonlight. Dodge increased by 15."),
        "earthquake": ("Earthquake", "The ground splits and armor cracks. Defense reduced by 35%."),
        "heatwave": ("Heatwave", "Scorching heat punishes heavy gear. Heavy items lose half their defense."),
        "fog": ("Thick Fog", "Nobody can see a thing. Accuracy -25, dodge +10."),
        "harvest": ("Harvest Festival", "A hearty feast before combat. Everyone gains +30 HP."),
        "bloodlust": ("Bloodlust", "Fury takes over. Attack +30%, defense -30%."),
        "blessing": ("Ancient Blessing", "Old spirits mend wounds. Everyone regenerates 5 HP per turn."),
        "poison_mist": ("Poison Mist", "Toxic fumes fill the arena. Everyone takes 4 poison damage per turn."),
        "gravity": ("Gravity Surge", "Bodies feel like lead. Nobody can dodge anything."),
        "mirror_world": ("Mirror World", "Reality flips. Everyone's attack and defense are swapped."),
        "giants_might": ("Giant's Might", "Everyone grows enormous. HP +50%, speed -25%."),
        "glass_cannon": ("Glass Cannon", "Power at a price. Attack +50%, HP -30%."),
        "merchants_gift": ("Merchant's Gift", "A traveling merchant polishes cheap gear. Common and Uncommon items gain 40% power."),
        "cursed_ground": ("Cursed Ground", "Dark soil devours all healing. No one can heal."),
        "vampire_night": ("Vampire Night", "Everyone thirsts for blood. All fighters gain 15% lifesteal."),
        "iron_sky": ("Iron Sky", "A dull grey sky dampens fortune. Critical chance is halved."),
        "storm_blades": ("Storm of Blades", "Phantom blades join every strike. +20% chance for extra attacks."),
        "pacifist_wind": ("Pacifist Wind", "A gentle breeze calms rage. Attack -20%, HP +25%."),
        "chaos_rift": ("Chaos Rift", "A rift warps reality. Every stat of every fighter shifts randomly by ±30%."),
        "golden_age": ("Golden Age", "Prestige rules. Epic and Legendary items +20%, Commons -10%."),
        "underdog": ("Underdog Spirit", "The crowd roots for the weak. The fighter with lower total power gains +30% everything."),
        "silence": ("Arcane Silence", "Magic fizzles out. All accessory passives are disabled."),
        "midnight_sun": ("Midnight Sun", "The sun refuses to set. Speed +30% and everyone hits 10% harder.")
    ]

    static let eventsTR: [String: (name: String, description: String)] = [
        "rain": ("Yağmur", "Sağanak her yay kirişini ıslattı. Menzilli silahlar %35 daha az hasar verir."),
        "blood_moon": ("Kanlı Ay", "Ay kızıla döndü. Kritik vuruşlar %50 daha fazla hasar verir."),
        "blizzard": ("Kar Fırtınası", "Dondurucu rüzgar herkesi yavaşlatıyor. Hız %35 azaldı."),
        "thunderstorm": ("Gök Gürültülü Fırtına", "Efsanevi eşyalar güçle çıtırdıyor: sahiplerine +%20 saldırı ve savunma."),
        "plague": ("Veba", "Salgın yayılıyor. Herkes %25 eksik canla başlar."),
        "lucky_day": ("Şanslı Gün", "Bugün mütevazılar parlıyor. Sıradan eşya sahipleri +%15 saldırı ve savunma kazanır."),
        "tax_season": ("Vergi Dönemi", "Kral zenginleri vergilendiriyor. Efsanevi eşya sahipleri %15 saldırı ve savunma kaybeder."),
        "tornado": ("Kasırga", "Kaotik rüzgar ilk vuranı belirliyor. Sıra her turda rastgele."),
        "eclipse": ("Güneş Tutulması", "Karanlık arenayı kapladı. İsabet 20 azaldı."),
        "full_moon": ("Dolunay", "Ay ışığında içgüdüler keskinleşir. Kaçınma 15 arttı."),
        "earthquake": ("Deprem", "Yer yarıldı, zırhlar çatladı. Savunma %35 azaldı."),
        "heatwave": ("Sıcak Hava Dalgası", "Kavurucu sıcak ağır zırhı cezalandırıyor. Ağır eşyalar savunmalarının yarısını kaybeder."),
        "fog": ("Yoğun Sis", "Kimse önünü göremiyor. İsabet -25, kaçınma +10."),
        "harvest": ("Hasat Şenliği", "Savaştan önce doyurucu bir ziyafet. Herkes +30 can kazanır."),
        "bloodlust": ("Kana Susamışlık", "Öfke kontrolü ele aldı. Saldırı +%30, savunma -%30."),
        "blessing": ("Kadim Kutsama", "Eski ruhlar yaraları sarıyor. Herkes her tur 5 can yeniler."),
        "poison_mist": ("Zehirli Sis", "Zehirli dumanlar arenayı doldurdu. Herkes her tur 4 zehir hasarı alır."),
        "gravity": ("Yerçekimi Dalgası", "Bedenler kurşun gibi. Kimse hiçbir şeyden kaçamaz."),
        "mirror_world": ("Ayna Dünyası", "Gerçeklik tersine döndü. Herkesin saldırısı ve savunması yer değiştirdi."),
        "giants_might": ("Devin Gücü", "Herkes devleşiyor. Can +%50, hız -%25."),
        "glass_cannon": ("Cam Top", "Gücün bedeli var. Saldırı +%50, can -%30."),
        "merchants_gift": ("Tüccarın Hediyesi", "Gezgin tüccar ucuz eşyaları parlattı. Sıradan ve Alışılmadık eşyalar %40 güç kazanır."),
        "cursed_ground": ("Lanetli Toprak", "Kara toprak tüm şifayı yutuyor. Kimse iyileşemez."),
        "vampire_night": ("Vampir Gecesi", "Herkes kana susadı. Tüm savaşçılar %15 can çalma kazanır."),
        "iron_sky": ("Demir Gökyüzü", "Kurşuni gökyüzü talihi söndürüyor. Kritik şansı yarıya indi."),
        "storm_blades": ("Kılıç Fırtınası", "Hayalet kılıçlar her vuruşa katılıyor. Ekstra saldırı şansı +%20."),
        "pacifist_wind": ("Barış Rüzgarı", "Tatlı bir esinti öfkeyi dindiriyor. Saldırı -%20, can +%25."),
        "chaos_rift": ("Kaos Yarığı", "Bir yarık gerçekliği büküyor. Herkesin tüm değerleri rastgele ±%30 değişir."),
        "golden_age": ("Altın Çağ", "İtibar konuşuyor. Destansı ve Efsanevi eşyalar +%20, Sıradanlar -%10."),
        "underdog": ("Ezilenin Ruhu", "Kalabalık zayıfı destekliyor. Toplam gücü düşük olan savaşçı her şeyde +%30 kazanır."),
        "silence": ("Gizemli Sessizlik", "Büyü sönüp gitti. Tüm aksesuar pasifleri devre dışı."),
        "midnight_sun": ("Gece Yarısı Güneşi", "Güneş batmayı reddediyor. Hız +%30 ve herkes %10 daha sert vurur.")
    ]

    static let luckCardsTR: [String: (name: String, description: String)] = [
        "pirate": ("Korsan", "Savaş başında rakibinin kuşandığı rastgele bir eşyayı çalarsın."),
        "blacksmith": ("Demirci", "Rastgele bir eşyan Efsanevi versiyonuna dönüştürülür."),
        "curse": ("Lanet", "Rakibinin en güçlü eşyasını tüm savaş boyunca devre dışı bırakır."),
        "lightning": ("Yıldırım", "Rakibin her savaşa %25 eksik canla başlar."),
        "lucky": ("Şanslı", "Kritik vuruş şansın iki katına çıkar."),
        "vampire": ("Vampir", "Verdiğin tüm hasarın %20'si kadar iyileşirsin."),
        "gambler": ("Kumarbaz", "Tüm eşya değerlerin %50 ile %200 arasında yeniden zarlanır. Bol şans."),
        "allin": ("HER ŞEYİNE", "Her savaşta: %50 ihtimalle saldırın ve canın %80 artar, yoksa %45 erir."),
        "magnet": ("Mıknatıs", "Rakibinin silahını tüm savaş boyunca devre dışı bırakır."),
        "trade": ("Takas", "Savaş başında rakibinle rastgele bir eşya değiş tokuş edersin."),
        "barrier": ("Bariyer", "Her savaşa 35 canlık büyülü bir kalkanla başlarsın."),
        "phoenix": ("Anka", "İlk ölümünde %40 canla yeniden dirilirsin."),
        "assassin": ("Suikastçı", "Her savaştaki ilk saldırın daima kritik vuruştur."),
        "titan": ("Titan", "+40 azami can, ama hızın %30 azalır.")
    ]

    static let passiveTemplates: [String: LangPair] = [
        "firstStrike": ("Always attacks first", "Her zaman ilk saldırır"),
        "lifesteal": ("Heals {v}% of damage dealt", "Verdiği hasarın %{v} kadarını can olarak çalar"),
        "reflect": ("Reflects {v}% of damage taken", "Aldığı hasarın %{v} kadarını yansıtır"),
        "poisonOnHit": ("Hits poison for {v} dmg per turn", "Vuruşları tur başına {v} zehir hasarı verir"),
        "extraAttack": ("{v}% chance to attack twice", "%{v} ihtimalle iki kez saldırır"),
        "healPerTurn": ("Regenerates {v} HP per turn", "Her tur {v} can yeniler"),
        "executioner": ("+{v}% dmg vs targets below 35% HP", "Canı %35 altındaki hedeflere +%{v} hasar"),
        "berserk": ("+{v}% attack below 40% HP", "Canı %40'ın altındayken +%{v} saldırı"),
        "ignoreDefense": ("Ignores {v}% of enemy defense", "Düşman savunmasının %{v} kadarını yok sayar"),
        "stunChance": ("{v}% chance to stun on hit", "Vuruşta %{v} sersemletme ihtimali"),
        "critResist": ("Takes {v}% less critical damage", "%{v} daha az kritik hasar alır"),
        "lastStand": ("Revives once at {v}% HP", "Bir kez %{v} canla dirilir"),
        "block": ("{v}% chance to block half damage", "%{v} ihtimalle hasarın yarısını engeller"),
        "chaos": ("All your stats shift ±{v}% each battle", "Tüm değerlerin her savaşta ±%{v} değişir"),
        "shield": ("Starts battle with a {v} HP shield", "Savaşa {v} canlık kalkanla başlar")
    ]

    static let logTemplates: [String: LangPair] = [
        "intro": ("⚔️ {a} VS {b}!", "⚔️ {a} VS {b}!"),
        "showcase": ("🎺 {p} enters the arena!", "🎺 {p} arenaya çıkıyor!"),
        "pirate": ("🏴‍☠️ {p} activates Pirate and steals {o}'s {emoji} {item}!", "🏴‍☠️ {p} Korsan kartını kullandı ve {o} oyuncusunun {emoji} {item} eşyasını çaldı!"),
        "trade": ("🎁 {p} activates Trade! {slot} items are swapped with {o}!", "🎁 {p} Takas kartını kullandı! {slot} eşyaları {o} ile değişti!"),
        "curse": ("💀 {p}'s Curse disables {o}'s {emoji} {item}!", "💀 {p} oyuncusunun Laneti, {o} oyuncusunun {emoji} {item} eşyasını devre dışı bıraktı!"),
        "magnet": ("🧲 {p}'s Magnet rips {o}'s {emoji} {item} away!", "🧲 {p} oyuncusunun Mıknatısı, {o} oyuncusunun {emoji} {item} silahını söküp aldı!"),
        "underdog": ("🐕 Underdog Spirit empowers {p}!", "🐕 Ezilenin Ruhu {p} oyuncusuna güç verdi!"),
        "lightning": ("⚡ {p}'s Lightning strikes {o} before the fight! -25% HP!", "⚡ {p} oyuncusunun Yıldırımı savaştan önce {o} oyuncusuna çarptı! -%25 can!"),
        "jackpot": ("🎰 {p} goes ALL IN... JACKPOT! Attack and HP surge!", "🎰 {p} HER ŞEYİNE oynadı... JACKPOT! Saldırı ve can fırladı!"),
        "bust": ("🎰 {p} goes ALL IN... and BUSTS! Attack and HP crumble!", "🎰 {p} HER ŞEYİNE oynadı... ve BATTI! Saldırı ve can eridi!"),
        "windupRanged": ("🏹 {p} draws the {weapon} and takes aim...", "🏹 {p}, {weapon} ile nişan alıyor..."),
        "windupHeavy": ("🪓 {p} raises the {weapon} for a massive swing...", "🪓 {p}, {weapon} silahını devasa bir savuruş için kaldırıyor..."),
        "windupBlade": ("⚔️ {p} lunges forward with the {weapon}...", "⚔️ {p}, {weapon} ile ileri atılıyor..."),
        "miss": ("💨 {p} swings the {weapon}... and misses!", "💨 {p}, {weapon} ile savurdu... ve ıskaladı!"),
        "dodgeLine": ("🌀 {d} dodges {p}'s attack!", "🌀 {d}, {p} oyuncusunun saldırısından kaçtı!"),
        "strike": ("⚔️ {p} strikes with the {weapon}! {d} loses {dmg} HP.", "⚔️ {p}, {weapon} ile vurdu! {d} {dmg} can kaybetti."),
        "lifesteal": ("🩸 {p} drains {heal} HP!", "🩸 {p} {heal} can emdi!"),
        "reflect": ("🌵 {d}'s armor reflects {dmg} damage back!", "🌵 {d} oyuncusunun zırhı {dmg} hasarı geri yansıttı!"),
        "poisonApplied": ("🐍 {d} is poisoned!", "🐍 {d} zehirlendi!"),
        "stunApplied": ("💫 {d} is stunned and will miss a turn!", "💫 {d} sersemledi, bir sonraki turu kaçıracak!"),
        "stunSkip": ("💫 {p} is stunned and staggers!", "💫 {p} sersemlemiş halde sendeliyor!"),
        "revive": ("🔥 {p} refuses to die and rises again with {hp} HP!", "🔥 {p} ölmeyi reddediyor ve {hp} canla yeniden ayağa kalkıyor!"),
        "poisonTick": ("☠️ Poison deals {dmg} damage to {p}!", "☠️ Zehir {p} oyuncusuna {dmg} hasar verdi!"),
        "fatigueTick": ("⏳ Fatigue and poison deals {dmg} damage to {p}!", "⏳ Yorgunluk ve zehir {p} oyuncusuna {dmg} hasar verdi!"),
        "regen": ("💚 {p} regenerates {heal} HP.", "💚 {p} {heal} can yeniledi."),
        "judges": ("⏱️ The judges call it! {p} takes it on remaining strength!", "⏱️ Hakemler kararını verdi! Kalan gücüyle {p} kazandı!"),
        "death": ("💀 {p} has fallen!", "💀 {p} düştü!"),
        "victoryLine": ("🏆 {p} WINS!", "🏆 {p} KAZANDI!")
    ]
}
